In [1]:
###General Mapping Function###
#this function will read a lookup table and do the mapping for you, so you don't need to write classification codes every time.
#the output is your main data with the mapped column

#the function will require the following 5 inputs:

#Main_data <- your main dataset (type: dataframe)
#Lookup_table <- your lookup table (type: dataframe)
#left_name <- the key in your main dataset (type: string)
#right_name <- the key in your lookup table (type: string)
#result_column_name <- which column do you want to put the results (type: string)

def Mapping(Main_data, Lookup_table, left_name, right_name, result_coloumn_name):
    df1 = Main_data
    df2 = Lookup_table
    results = df1.merge(df2, left_on = left_name, right_on = right_name, how = 'left')
    result_column = results.iloc[:,-1]
    Main_data[result_coloumn_name] = result_column

In [2]:
###Create Lookup Table Function###
#this function will create a lookup table as dataframe for you

#the function will require the following 3 inputs:

#Lookup_file <- your lookup file location (type: string)
#sheet_name <- your sheet name in the file
#n <- which column you want to return
def create_Lookup_table(Lookup_file, sheet_name, n):
    df = pd.read_excel(Lookup_file,sheet_name = sheet_name)
    df = df.iloc[:,[0,n-1]]
    return df

In [3]:
#Import libraries needed 
import pandas as pd
import numpy as np
import datetime
from datetime import datetime,timedelta
import os

In [4]:
master_path = 'D:/shycopy/new life/Python/nba/Data_Exploration'
raw_data_folder = 'PlaybyPlay_rawdata'
os.chdir(master_path)

In [5]:
#read the files
os.chdir(raw_data_folder)

In [6]:
combined_df = pd.DataFrame()
for i in range(len(os.listdir())):
    combined_df = pd.concat([combined_df,pd.read_csv(os.listdir()[i], low_memory = False)], ignore_index=True)
    i = i+1

In [7]:
combined_df.head()

,Unnamed: 0,EVENTMSGACTIONTYPE,EVENTMSGTYPE,EVENTNUM,GAME_ID,HOMEDESCRIPTION,NEUTRALDESCRIPTION,PCTIMESTRING,PERIOD,PERSON1TYPE,...,HOME_PLAYER_ID_1_PLAY_TIME,HOME_PLAYER_ID_2_PLAY_TIME,HOME_PLAYER_ID_3_PLAY_TIME,HOME_PLAYER_ID_4_PLAY_TIME,HOME_PLAYER_ID_5_PLAY_TIME,AWAY_PLAYER_ID_1_PLAY_TIME,AWAY_PLAYER_ID_2_PLAY_TIME,AWAY_PLAYER_ID_3_PLAY_TIME,AWAY_PLAYER_ID_4_PLAY_TIME,AWAY_PLAYER_ID_5_PLAY_TIME
0,0,0,12,0,21500001,NaN,NaN,12:00,1,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,0,10,1,21500001,Jump Ball Horford vs. Drummond: Tip to Ilyasova,NaN,12:00,1,4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2,42,2,2,21500001,Horford BLOCK (1 BLK),NaN,11:41,1,5.0,...,19.0,19.0,19.0,19.0,19.0,19.0,19.0,19.0,19.0,19.0
3,3,0,4,3,21500001,Bazemore REBOUND (Off:0 Def:1),NaN,11:39,1,4.0,...,21.0,21.0,21.0,21.0,21.0,21.0,21.0,21.0,21.0,21.0
4,4,45,5,4,21500001,Bazemore Out of Bounds - Bad Pass Turnover Tur...,NaN,11:37,1,4.0,...,23.0,23.0,23.0,23.0,23.0,23.0,23.0,23.0,23.0,23.0

In [6]:
list(combined_df)

['Unnamed: 0',
 'EVENTMSGACTIONTYPE',
 'EVENTMSGTYPE',
 'EVENTNUM',
 'GAME_ID',
 'HOMEDESCRIPTION',
 'NEUTRALDESCRIPTION',
 'PCTIMESTRING',
 'PERIOD',
 'PERSON1TYPE',
 'PERSON2TYPE',
 'PERSON3TYPE',
 'PLAYER1_ID',
 'PLAYER1_NAME',
 'PLAYER1_TEAM_ABBREVIATION',
 'PLAYER1_TEAM_CITY',
 'PLAYER1_TEAM_ID',
 'PLAYER1_TEAM_NICKNAME',
 'PLAYER2_ID',
 'PLAYER2_NAME',
 'PLAYER2_TEAM_ABBREVIATION',
 'PLAYER2_TEAM_CITY',
 'PLAYER2_TEAM_ID',
 'PLAYER2_TEAM_NICKNAME',
 'PLAYER3_ID',
 'PLAYER3_NAME',
 'PLAYER3_TEAM_ABBREVIATION',
 'PLAYER3_TEAM_CITY',
 'PLAYER3_TEAM_ID',
 'PLAYER3_TEAM_NICKNAME',
 'SCORE',
 'SCOREMARGIN',
 'VISITORDESCRIPTION',
 'WCTIMESTRING',
 'HOME_TEAM',
 'AWAY_TEAM',
 'HOME_SCORE',
 'AWAY_SCORE',
 'TIME',
 'TEAM',
 'TYPE',
 'SUB_TYPE',
 'ASSIST_PLAYER_ID',
 'ASSIST_COUNT',
 'BLOCK_PLAYER_ID',
 'BLOCK_COUNT',
 'REBOUND_PLAYER_ID',
 'REBOUND_TEAM',
 'REBOUND_OFFENSIVE_COUNT',
 'REBOUND_DEFENSIVE_COUNT',
 'JUMP_BALL_HOME_PLAYER_ID',
 'JUMP_BALL_AWAY_PLAYER_ID',
 'JUMP_BALL_RETRIEVED_PLAYER_ID',
 'SUB_ENTERED_PLAYER_ID',
 'SUB_LEAVING_PLAYER_ID',
 'FREE_THROW_PLAYER_ID',
 'FREE_THROW_NUM',
 'FREE_THROW_TOTAL',
 'FREE_THROW_MADE',
 'FOULED_BY_PLAYER_ID',
 'DRAWN_FOUL_PLAYER_ID',
 'FOUL_COUNT',
 'TEAM_FOUL_COUNT',
 'FOUL_TYPE',
 'TECHNICAL_PLAYER_ID',
 'DOUBLE_TECHNICAL_PLAYER_ID_1',
 'DOUBLE_TECHNICAL_PLAYER_ID_2',
 'DOUBLE_PERSONAL_PLAYER_ID_1',
 'DOUBLE_PERSONAL_PLAYER_ID_2',
 'DOUBLE_PERSONAL_FOUL_COUNT_1',
 'DOUBLE_PERSONAL_FOUL_COUNT_2',
 'COACH_TECHNICAL',
 'SHOT_PLAYER_ID',
 'POINTS_SCORED',
 'TOTAL_POINTS_SCORED',
 'SHOT_MADE',
 'SHOT_TYPE',
 'STEAL_PLAYER_ID',
 'STEAL_COUNT',
 'TURNOVER_PLAYER_ID',
 'TURNOVER_COUNT',
 'TEAM_TURNOVER_COUNT',
 'TURNOVER_TYPE',
 'POSSESSION_ID',
 'PERIOD_START',
 'PERIOD_END',
 'TIMEOUT_TYPE',
 'VIOLATION',
 'VIOLATION_PLAYER_ID',
 'EJECTION',
 'EJECTION_PLAYER_ID',
 'HOME_PLAYER_ID_1',
 'HOME_PLAYER_ID_2',
 'HOME_PLAYER_ID_3',
 'HOME_PLAYER_ID_4',
 'HOME_PLAYER_ID_5',
 'AWAY_PLAYER_ID_1',
 'AWAY_PLAYER_ID_2',
 'AWAY_PLAYER_ID_3',
 'AWAY_PLAYER_ID_4',
 'AWAY_PLAYER_ID_5',
 'HOME_PLAYER_ID_1_PLAY_TIME',
 'HOME_PLAYER_ID_2_PLAY_TIME',
 'HOME_PLAYER_ID_3_PLAY_TIME',
 'HOME_PLAYER_ID_4_PLAY_TIME',
 'HOME_PLAYER_ID_5_PLAY_TIME',
 'AWAY_PLAYER_ID_1_PLAY_TIME',
 'AWAY_PLAYER_ID_2_PLAY_TIME',
 'AWAY_PLAYER_ID_3_PLAY_TIME',
 'AWAY_PLAYER_ID_4_PLAY_TIME',
 'AWAY_PLAYER_ID_5_PLAY_TIME']